import { useState } from 'react'
import { Link } from 'react-router-dom'
import { CheckIcon } from './Icons'
import { toneFor, productPath, formatPrice } from '../utils/product'
import { useCart } from '../context/CartContext'
export function ProductImage({ product, className = '' }) { const [failed, setFailed] = useState(false); if (product.image_url && !failed) return <img className={`product-image ${className}`} src={product.image_url} alt={product.name} loading="lazy" onError={() => setFailed(true)} />; return <div className={`product-image placeholder ${className}`} style={{ background: toneFor(product.name) }} role="img" aria-label={product.name}>{product.name.charAt(0).toUpperCase()}</div> }
export default function ProductCard({ product, onAdd }) {
  const { items, add, remove } = useCart(); const [busy, setBusy] = useState(false); const [error, setError] = useState(''); const qty = items.find((i) => i.name === product.name)?.qty || 0
  const run = async (action) => { setBusy(true); setError(''); try { await action() } catch (e) { setError(e.message) } finally { setBusy(false) } }
  return <article className="product-card"><Link to={productPath(product)} className="product-link"><ProductImage product={product} /><h3>{product.name}</h3>{product.price !== null && <p className="price">{formatPrice(product.price)}</p>}</Link>{qty > 0 ? <div className="stepper product-stepper"><button type="button" disabled={busy} onClick={() => run(() => remove(product.name, 1))} aria-label={`Decrease ${product.name}`}>−</button><output>{qty}</output><button type="button" disabled={busy || (product.stock !== null && qty >= product.stock)} onClick={() => run(() => (onAdd ? onAdd(product, 1) : add(product, 1)))} aria-label={`Increase ${product.name}`}>+</button></div> : <button className="button button-outline small" type="button" disabled={busy} onClick={() => run(() => (onAdd ? onAdd(product, 1) : add(product, 1)))}>{busy ? 'Adding…' : <><CheckIcon width={16} height={16} /> Add to cart</>}</button>}{error && <p className="field-error" role="alert">{error}</p>}</article>
}