import axios from 'axios'
export const api = axios.create({ baseURL: import.meta.env.VITE_API_BASE_URL || 'http://localhost:3000' })
const key = 'simplecart_customer_access'; const refreshKey = 'simplecart_customer_refresh'
export const storage = { get access() { return localStorage.getItem(key) }, get refresh() { return localStorage.getItem(refreshKey) }, set(data) { if (data?.access_token) localStorage.setItem(key, data.access_token); if (data?.refresh_token) localStorage.setItem(refreshKey, data.refresh_token) }, clear() { localStorage.removeItem(key); localStorage.removeItem(refreshKey) } }
api.interceptors.request.use(config => { const token = config.userType === 'admin' ? localStorage.getItem('simplecart_admin_access') : storage.access; if (token) config.headers.Authorization = `Bearer ${token}`; return config })
let refreshing = false; let waiting = []
api.interceptors.response.use(response => response, async error => { const original = error.config; if (!original || original._retry || original.url?.includes('/refresh') || !storage.refresh || ![401, 403, 500].includes(error.response?.status)) throw error; original._retry = true; if (refreshing) return new Promise((resolve, reject) => waiting.push({ resolve, reject })).then(token => { original.headers.Authorization = `Bearer ${token}`; return api(original) }); refreshing = true; try { const result = await axios.post(`${api.defaults.baseURL}/cus/refresh`, { refresh_token: storage.refresh }); storage.set(result.data?.data); waiting.splice(0).forEach(({ resolve }) => resolve(storage.access)); original.headers.Authorization = `Bearer ${storage.access}`; return api(original) } catch (refreshError) { waiting.splice(0).forEach(({ reject }) => reject(refreshError)); storage.clear(); window.location.href = '/login'; throw refreshError } finally { refreshing = false } })
export const responseData = response => { if (response.data?.status >= 400) throw new Error(response.data.msg || 'Request failed'); return response.data?.data ?? {} }
export const apiError = error => new Error(error.response?.data?.msg || error.response?.data?.message || error.message || 'Something went wrong')
