import { useEffect, useState } from 'react'
import { Link, Navigate, Route, Routes, useNavigate, useParams } from 'react-router-dom'
import { AuthProvider, useAuth } from './context/AuthContext'
import { CartProvider, useCart } from './context/CartContext'
import { catalogApi } from './services/catalogApi'
import { cartApi } from './services/cartApi'
import { adminApi } from './services/adminApi'
import './App.css'

const Loading = ({ text = 'Loading...' }) => <p className="notice">{text}</p>
const ErrorMessage = ({ message, onRetry }) => <div className="notice error"><p>{message}</p>{onRetry && <button onClick={onRetry}>Try again</button>}</div>

function Layout({ children }) {
  const { isAuthenticated, user, userType, logout } = useAuth(); const { items } = useCart(); const navigate = useNavigate()
  return <><header className="site-header"><div className="container nav-row"><Link className="brand" to="/">simplecart</Link><nav><Link to="/categories">Categories</Link>{isAuthenticated && userType === 'customer' && <Link to="/cart">Cart ({items.length})</Link>}{isAuthenticated && userType === 'admin' && <Link to="/admin">Admin</Link>}{isAuthenticated ? <button className="link-button" onClick={() => { logout(); navigate('/') }}>Log out</button> : <><Link to="/login">Log in</Link><Link className="button small" to="/register">Create account</Link></>}{isAuthenticated && <span className="user-label">{user?.email}</span>}</nav></div></header><main>{children}</main><footer><div className="container">simplecart · A straightforward shopping experience.</div></footer></>
}
function Home() { return <div className="container"><section className="hero"><p className="eyebrow">Simple shopping</p><h1>Find something useful.</h1><p>Browse the connected catalog, add products to your cart, and check out securely.</p><Link className="button" to="/categories">Browse categories</Link></section><section className="info-grid"><div><h2>Clear catalog</h2><p>Products are shown from the backend without made-up prices or details.</p></div><div><h2>Easy checkout</h2><p>Your order total is calculated by the server.</p></div><div><h2>Responsive by default</h2><p>A clean layout for phones, tablets, and desktop screens.</p></div></section></div> }
function AuthForm({ admin = false }) { const { login, register } = useAuth(); const navigate = useNavigate(); const [mode, setMode] = useState('login'); const [form, setForm] = useState({ name:'', email:'', password:'', main_address:'', secondary_address:'', DOB:'', employee_id:'' }); const [error, setError] = useState(''); const [busy, setBusy] = useState(false); const submit = async e => { e.preventDefault(); setError(''); setBusy(true); try { if (mode === 'login') await login({ name: form.name, email: form.email, password: form.password }, admin ? 'admin' : 'customer'); else await register(form, admin ? 'admin' : 'customer'); navigate(admin ? '/admin' : '/') } catch (err) { setError(err.message) } finally { setBusy(false) } }; const update = e => setForm({ ...form, [e.target.name]: e.target.value }); return <div className="form-page"><form className="form-card" onSubmit={submit}><p className="eyebrow">{admin ? 'Admin area' : 'Your account'}</p><h1>{mode === 'login' ? 'Log in' : 'Create account'}</h1>{error && <ErrorMessage message={error} />}{(mode === 'login' || mode === 'register') && <label>Name<input name="name" required value={form.name} onChange={update} /></label>}{mode === 'register' && <>{admin ? <label>Employee ID<input name="employee_id" required pattern="EMP[0-9]{6}" placeholder="EMP123456" value={form.employee_id} onChange={update} /></label> : <><label>Main address<input name="main_address" required value={form.main_address} onChange={update} /></label><label>Secondary address<input name="secondary_address" required value={form.secondary_address} onChange={update} /></label><label>Date of birth<input type="date" name="DOB" required value={form.DOB} onChange={update} /></label></>}</>}<label>Email<input type="email" name="email" required value={form.email} onChange={update} /></label><label>Password<input type="password" name="password" required value={form.password} onChange={update} /></label><button className="button" disabled={busy}>{busy ? 'Please wait...' : mode === 'login' ? 'Log in' : 'Create account'}</button>{!admin && <button type="button" className="text-button" onClick={() => setMode(mode === 'login' ? 'register' : 'login')}>{mode === 'login' ? 'Need an account? Create one' : 'Already have an account? Log in'}</button>}</form></div> }
function Page({ title, back, children }) { return <div className="container page"><div className="page-heading">{back && <Link to={back}>← Back</Link>}<h1>{title}</h1></div>{children}</div> }
function Categories() { const [categories, setCategories] = useState([]); const [error, setError] = useState(''); const load = () => catalogApi.getCategories().then(setCategories).catch(e => setError(e.message)); useEffect(load, []); return <Page title="Categories">{error ? <ErrorMessage message={error} onRetry={load} /> : !categories.length ? <Loading text="No categories found." /> : <div className="card-grid">{categories.map(category => <Link className="category-card" key={category} to={`/category/${encodeURIComponent(category)}`}><h2>{category}</h2><span>View subcategories →</span></Link>)}</div>}</Page> }
function Subcategories() { const { categoryId } = useParams(); const [subs, setSubs] = useState([]); const [error, setError] = useState(''); const load = () => catalogApi.getSubcategories(categoryId).then(setSubs).catch(e => setError(e.message)); useEffect(load, [categoryId]); return <Page title={decodeURIComponent(categoryId)} back="/categories">{error ? <ErrorMessage message={error} onRetry={load} /> : !subs.length ? <Loading text="No subcategories found." /> : <div className="card-grid">{subs.map(sub => <Link className="category-card" key={sub} to={`/category/${categoryId}/subcategory/${encodeURIComponent(sub)}`}><h2>{sub}</h2><span>View products →</span></Link>)}</div>}</Page> }
function Products() { const { categoryId, subcategoryId } = useParams(); const [products, setProducts] = useState([]); const [error, setError] = useState(''); const load = () => catalogApi.getProducts(categoryId, subcategoryId).then(setProducts).catch(e => setError(e.message)); useEffect(load, [categoryId, subcategoryId]); return <Page title={decodeURIComponent(subcategoryId)} back={`/category/${categoryId}`}>{error ? <ErrorMessage message={error} onRetry={load} /> : !products.length ? <Loading text="No products found." /> : <div className="product-grid">{products.map(product => <ProductCard key={product.name} product={product} />)}</div>}</Page> }
function ProductCard({ product }) { const { add } = useCart(); const [message, setMessage] = useState(''); return <article className="product-card">{product.image_url ? <img src={product.image_url} alt="" /> : <div className="image-placeholder">No image</div>}<div className="product-body"><h2>{product.name}</h2><p className="muted">Pricing is provided by the backend during checkout.</p><button className="button small" onClick={async () => { try { await add(product.name); setMessage('Added to cart') } catch (e) { setMessage(e.message) } }}>{message || 'Add to cart'}</button></div></article> }
function Cart() { const { items, remove } = useCart(); return <Page title="Your cart">{!items.length ? <div className="empty"><h2>Your cart is empty</h2><Link to="/categories">Browse categories</Link></div> : <><div className="cart-list">{items.map(item => <div className="cart-row" key={item.name}><div><h2>{item.name}</h2><p>Quantity: {item.qty}</p></div><button className="text-button danger" onClick={() => remove(item.name)}>Remove</button></div>)}</div><Link className="button" to="/checkout">Continue to checkout</Link></>}</Page> }
function Checkout() { const { items, clear } = useCart(); const navigate = useNavigate(); const [busy, setBusy] = useState(false); const [error, setError] = useState(''); if (!items.length) return <Navigate to="/cart" replace />; const submit = async () => { setBusy(true); try { const receipt = await cartApi.checkout(); clear(); navigate('/order/success', { state: { receipt } }) } catch (e) { setError(e.message) } finally { setBusy(false) } }; return <Page title="Checkout"><div className="checkout"><section><h2>Items</h2>{items.map(item => <p key={item.name}>{item.name} × {item.qty}</p>)}</section><aside className="summary"><h2>Order summary</h2><p>The final cost, tax, and shipping are calculated by the server.</p>{error && <ErrorMessage message={error} />}<button className="button" disabled={busy} onClick={submit}>{busy ? 'Processing...' : 'Place order'}</button></aside></div></Page> }
function OrderSuccess() { return <Page title="Order confirmed"><div className="success"><p>Your order was sent successfully.</p><p>The server returned the receipt.</p><Link className="button" to="/categories">Continue shopping</Link></div></Page> }
function ProtectedRoute({ children, type = 'customer' }) { const { isAuthenticated, userType } = useAuth(); if (!isAuthenticated) return <Navigate to={type === 'admin' ? '/admin/login' : '/login'} replace />; if (userType !== type) return <Navigate to="/" replace />; return children }
function Admin() { const [category, setCategory] = useState(''); const [message, setMessage] = useState(''); return <Page title="Admin dashboard"><div className="admin-grid"><Link className="category-card" to="/admin/categories"><h2>Categories</h2><span>Manage category names</span></Link><Link className="category-card" to="/admin/products"><h2>Products</h2><span>Manage products</span></Link></div><div className="form-card compact"><h2>Quick add category</h2><input value={category} onChange={e => setCategory(e.target.value)} placeholder="Category name" /><button className="button" onClick={async () => { try { await adminApi.createCategories([category]); setMessage('Category created'); setCategory('') } catch (e) { setMessage(e.message) } }}>Add category</button>{message && <p className="muted">{message}</p>}</div></Page> }
function AdminCategories() { const [name, setName] = useState(''); const [message, setMessage] = useState(''); return <Page title="Manage categories" back="/admin"><div className="form-card compact"><label>New category<input value={name} onChange={e => setName(e.target.value)} /></label><button className="button" onClick={async () => { try { await adminApi.createCategories([name]); setMessage('Saved'); setName('') } catch (e) { setMessage(e.message) } }}>Create</button>{message && <p>{message}</p>}</div></Page> }
function AdminProducts() { return <Page title="Manage products" back="/admin"><div className="empty"><h2>Product management</h2><p>Connect the multipart fields documented by the backend: prod, stock, brand, desc, price, and images.</p></div></Page> }
function AppRoutes() { return <Layout><Routes><Route path="/" element={<Home />} /><Route path="/login" element={<AuthForm />} /><Route path="/register" element={<AuthForm />} /><Route path="/categories" element={<Categories />} /><Route path="/category/:categoryId" element={<Subcategories />} /><Route path="/category/:categoryId/subcategory/:subcategoryId" element={<Products />} /><Route path="/cart" element={<ProtectedRoute><Cart /></ProtectedRoute>} /><Route path="/checkout" element={<ProtectedRoute><Checkout /></ProtectedRoute>} /><Route path="/order/success" element={<ProtectedRoute><OrderSuccess /></ProtectedRoute>} /><Route path="/admin/login" element={<AuthForm admin />} /><Route path="/admin" element={<ProtectedRoute type="admin"><Admin /></ProtectedRoute>} /><Route path="/admin/categories" element={<ProtectedRoute type="admin"><AdminCategories /></ProtectedRoute>} /><Route path="/admin/products" element={<ProtectedRoute type="admin"><AdminProducts /></ProtectedRoute>} /><Route path="*" element={<Navigate to="/" replace />} /></Routes></Layout> }
export default function App() { return <AuthProvider><CartProvider><AppRoutes /></CartProvider></AuthProvider> }
